# This file was generated by CMake because it detected try_run() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# CLANG_HAS_DISABLE_TAIL_CALLS_CFG_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CLANG_HAS_DISABLE_TAIL_CALLS_CFG_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CLANG_HAS_DISABLE_TAIL_CALLS_CFG_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set CLANG_HAS_DISABLE_TAIL_CALLS_CFG_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# CLANG_HAS_DISABLE_TAIL_CALLS_CFG_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set CLANG_HAS_DISABLE_TAIL_CALLS_CFG_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CLANG_HAS_DISABLE_TAIL_CALLS_CFG_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_58f13-CLANG_HAS_DISABLE_TAIL_CALLS_CFG_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/Build/CMakeFeatureDetect.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( CLANG_HAS_DISABLE_TAIL_CALLS_CFG_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# REALPATH_SUPPORTS_NONEXISTENT_FILES_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set REALPATH_SUPPORTS_NONEXISTENT_FILES_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# REALPATH_SUPPORTS_NONEXISTENT_FILES_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set REALPATH_SUPPORTS_NONEXISTENT_FILES_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# REALPATH_SUPPORTS_NONEXISTENT_FILES_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set REALPATH_SUPPORTS_NONEXISTENT_FILES_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The REALPATH_SUPPORTS_NONEXISTENT_FILES_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_875eb-REALPATH_SUPPORTS_NONEXISTENT_FILES_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( REALPATH_SUPPORTS_NONEXISTENT_FILES_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# SSCANF_SUPPORT_ll_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set SSCANF_SUPPORT_ll_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# SSCANF_SUPPORT_ll_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set SSCANF_SUPPORT_ll_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# SSCANF_SUPPORT_ll_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set SSCANF_SUPPORT_ll_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The SSCANF_SUPPORT_ll_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_0dbb6-SSCANF_SUPPORT_ll_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( SSCANF_SUPPORT_ll_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_27198-SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_LARGE_SNPRINTF_SUPPORT_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_LARGE_SNPRINTF_SUPPORT_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_LARGE_SNPRINTF_SUPPORT_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_LARGE_SNPRINTF_SUPPORT_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_LARGE_SNPRINTF_SUPPORT_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_LARGE_SNPRINTF_SUPPORT_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_LARGE_SNPRINTF_SUPPORT_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_17fcc-HAVE_LARGE_SNPRINTF_SUPPORT_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_LARGE_SNPRINTF_SUPPORT_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_BROKEN_FIFO_KEVENT_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_BROKEN_FIFO_KEVENT_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_BROKEN_FIFO_KEVENT_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_BROKEN_FIFO_KEVENT_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_BROKEN_FIFO_KEVENT_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_BROKEN_FIFO_KEVENT_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_BROKEN_FIFO_KEVENT_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_8cd71-HAVE_BROKEN_FIFO_KEVENT_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_BROKEN_FIFO_KEVENT_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_SCHED_GET_PRIORITY_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_SCHED_GET_PRIORITY_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_SCHED_GET_PRIORITY_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_SCHED_GET_PRIORITY_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_SCHED_GET_PRIORITY_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_SCHED_GET_PRIORITY_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_SCHED_GET_PRIORITY_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_2d4df-HAVE_SCHED_GET_PRIORITY_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_SCHED_GET_PRIORITY_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_WORKING_GETTIMEOFDAY_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_WORKING_GETTIMEOFDAY_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_WORKING_GETTIMEOFDAY_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_WORKING_GETTIMEOFDAY_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_WORKING_GETTIMEOFDAY_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_WORKING_GETTIMEOFDAY_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_WORKING_GETTIMEOFDAY_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_58a6e-HAVE_WORKING_GETTIMEOFDAY_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_WORKING_GETTIMEOFDAY_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_WORKING_CLOCK_GETTIME_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_WORKING_CLOCK_GETTIME_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_WORKING_CLOCK_GETTIME_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_WORKING_CLOCK_GETTIME_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_WORKING_CLOCK_GETTIME_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_WORKING_CLOCK_GETTIME_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_WORKING_CLOCK_GETTIME_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_dfe07-HAVE_WORKING_CLOCK_GETTIME_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_WORKING_CLOCK_GETTIME_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_CLOCK_MONOTONIC_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_CLOCK_MONOTONIC_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_CLOCK_MONOTONIC_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_CLOCK_MONOTONIC_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_CLOCK_MONOTONIC_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_CLOCK_MONOTONIC_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_CLOCK_MONOTONIC_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_f0b74-HAVE_CLOCK_MONOTONIC_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_CLOCK_MONOTONIC_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_CLOCK_MONOTONIC_COARSE_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_CLOCK_MONOTONIC_COARSE_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_CLOCK_MONOTONIC_COARSE_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_CLOCK_MONOTONIC_COARSE_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_CLOCK_MONOTONIC_COARSE_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_CLOCK_MONOTONIC_COARSE_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_CLOCK_MONOTONIC_COARSE_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_ebb59-HAVE_CLOCK_MONOTONIC_COARSE_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_CLOCK_MONOTONIC_COARSE_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_MACH_ABSOLUTE_TIME_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_MACH_ABSOLUTE_TIME_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_MACH_ABSOLUTE_TIME_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_MACH_ABSOLUTE_TIME_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_MACH_ABSOLUTE_TIME_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_MACH_ABSOLUTE_TIME_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_MACH_ABSOLUTE_TIME_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_16297-HAVE_MACH_ABSOLUTE_TIME_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_MACH_ABSOLUTE_TIME_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_CLOCK_THREAD_CPUTIME_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_CLOCK_THREAD_CPUTIME_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_CLOCK_THREAD_CPUTIME_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_CLOCK_THREAD_CPUTIME_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_CLOCK_THREAD_CPUTIME_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_CLOCK_THREAD_CPUTIME_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_CLOCK_THREAD_CPUTIME_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_10043-HAVE_CLOCK_THREAD_CPUTIME_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_CLOCK_THREAD_CPUTIME_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_MMAP_DEV_ZERO_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_MMAP_DEV_ZERO_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_MMAP_DEV_ZERO_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_MMAP_DEV_ZERO_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_MMAP_DEV_ZERO_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_MMAP_DEV_ZERO_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_MMAP_DEV_ZERO_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_39ac8-HAVE_MMAP_DEV_ZERO_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_MMAP_DEV_ZERO_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# MMAP_IGNORES_HINT_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set MMAP_IGNORES_HINT_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# MMAP_IGNORES_HINT_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set MMAP_IGNORES_HINT_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# MMAP_IGNORES_HINT_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set MMAP_IGNORES_HINT_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The MMAP_IGNORES_HINT_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_50792-MMAP_IGNORES_HINT_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( MMAP_IGNORES_HINT_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# MMAP_DOESNOT_ALLOW_REMAP_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set MMAP_DOESNOT_ALLOW_REMAP_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# MMAP_DOESNOT_ALLOW_REMAP_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set MMAP_DOESNOT_ALLOW_REMAP_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# MMAP_DOESNOT_ALLOW_REMAP_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set MMAP_DOESNOT_ALLOW_REMAP_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The MMAP_DOESNOT_ALLOW_REMAP_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_10fff-MMAP_DOESNOT_ALLOW_REMAP_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( MMAP_DOESNOT_ALLOW_REMAP_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_9046c-ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# PTHREAD_CREATE_MODIFIES_ERRNO_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set PTHREAD_CREATE_MODIFIES_ERRNO_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# PTHREAD_CREATE_MODIFIES_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set PTHREAD_CREATE_MODIFIES_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# PTHREAD_CREATE_MODIFIES_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set PTHREAD_CREATE_MODIFIES_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The PTHREAD_CREATE_MODIFIES_ERRNO_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_15796-PTHREAD_CREATE_MODIFIES_ERRNO_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( PTHREAD_CREATE_MODIFIES_ERRNO_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# SEM_INIT_MODIFIES_ERRNO_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set SEM_INIT_MODIFIES_ERRNO_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# SEM_INIT_MODIFIES_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set SEM_INIT_MODIFIES_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# SEM_INIT_MODIFIES_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set SEM_INIT_MODIFIES_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The SEM_INIT_MODIFIES_ERRNO_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_fd57a-SEM_INIT_MODIFIES_ERRNO_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( SEM_INIT_MODIFIES_ERRNO_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_COMPATIBLE_ACOS_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_COMPATIBLE_ACOS_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_COMPATIBLE_ACOS_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_ACOS_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_COMPATIBLE_ACOS_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_ACOS_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_COMPATIBLE_ACOS_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_59e47-HAVE_COMPATIBLE_ACOS_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_COMPATIBLE_ACOS_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_COMPATIBLE_ASIN_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_COMPATIBLE_ASIN_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_COMPATIBLE_ASIN_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_ASIN_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_COMPATIBLE_ASIN_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_ASIN_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_COMPATIBLE_ASIN_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_f4c45-HAVE_COMPATIBLE_ASIN_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_COMPATIBLE_ASIN_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_COMPATIBLE_ATAN2_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_COMPATIBLE_ATAN2_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_COMPATIBLE_ATAN2_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_ATAN2_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_COMPATIBLE_ATAN2_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_ATAN2_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_COMPATIBLE_ATAN2_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_4f67d-HAVE_COMPATIBLE_ATAN2_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_COMPATIBLE_ATAN2_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_COMPATIBLE_LOG_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_COMPATIBLE_LOG_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_COMPATIBLE_LOG_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_LOG_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_COMPATIBLE_LOG_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_LOG_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_COMPATIBLE_LOG_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_3e4bf-HAVE_COMPATIBLE_LOG_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_COMPATIBLE_LOG_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAVE_COMPATIBLE_LOG10_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_COMPATIBLE_LOG10_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAVE_COMPATIBLE_LOG10_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_LOG10_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAVE_COMPATIBLE_LOG10_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAVE_COMPATIBLE_LOG10_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_COMPATIBLE_LOG10_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_50d2c-HAVE_COMPATIBLE_LOG10_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAVE_COMPATIBLE_LOG10_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# UNGETC_NOT_RETURN_EOF_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set UNGETC_NOT_RETURN_EOF_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# UNGETC_NOT_RETURN_EOF_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set UNGETC_NOT_RETURN_EOF_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# UNGETC_NOT_RETURN_EOF_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set UNGETC_NOT_RETURN_EOF_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The UNGETC_NOT_RETURN_EOF_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_36999-UNGETC_NOT_RETURN_EOF_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( UNGETC_NOT_RETURN_EOF_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# HAS_POSIX_SEMAPHORES_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAS_POSIX_SEMAPHORES_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HAS_POSIX_SEMAPHORES_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set HAS_POSIX_SEMAPHORES_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# HAS_POSIX_SEMAPHORES_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set HAS_POSIX_SEMAPHORES_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAS_POSIX_SEMAPHORES_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_de835-HAS_POSIX_SEMAPHORES_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( HAS_POSIX_SEMAPHORES_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# GETPWUID_R_SETS_ERRNO_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set GETPWUID_R_SETS_ERRNO_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# GETPWUID_R_SETS_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set GETPWUID_R_SETS_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# GETPWUID_R_SETS_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set GETPWUID_R_SETS_ERRNO_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The GETPWUID_R_SETS_ERRNO_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_0b67a-GETPWUID_R_SETS_ERRNO_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( GETPWUID_R_SETS_ERRNO_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)


# FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_EXITCODE__TRYRUN_OUTPUT_STDOUT
#    contains the text the executable would have printed on stdout.
#    If the executable would not have been able to run, set FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_EXITCODE__TRYRUN_OUTPUT_STDOUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_EXITCODE__TRYRUN_OUTPUT_STDERR
#    contains the text the executable would have printed on stderr.
#    If the executable would not have been able to run, set FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_EXITCODE__TRYRUN_OUTPUT_STDERR empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_COMPILED variable holds the build result for this try_run().
# 
# Executable    : /Volumes/S/chakra/build_chjitx64/CMakeFiles/cmTC_e60f7-FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_EXITCODE
# Run arguments : 
#    Called from: [4]	/Volumes/S/chakra/ChakraCore/CMakeLists.txt
#                 [3]	/Volumes/S/chakra/ChakraCore/pal/src/configure.cmake
#                 [2]	/usr/local/share/cmake/Modules/CheckCXXSourceRuns.cmake
#                 [1]	/usr/local/share/cmake/Modules/Internal/CheckSourceRuns.cmake

set( FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from try_run" FORCE)

